### ISSUE TITLE
Cancel button in "Backup" screen not working

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#1]
The "Cancel" button in the backup details screen for a server is not working. Clicking it does nothing, so the page can't be closed. I have to force close the app and start again.

Details: iOS 11.2.5 on iPhone 8

![screenshot-2018-02-01](https://user-images.githubusercontent.com/1172106/35672247-380d1828-073e-11e8-8058-22e5a7b0a2fb.jpg)

**Comment by LKDevelopment** [comment]
Thank you, fixed in the master branch.
