### ISSUE TITLE
Confusing swipe-actions on server list

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#14]
I find it confusing not being able to directly click on a server in the servers list. You have to swipe left and then click on the info icon. Maybe remove those swipe actions and move the "delete" option into the floating action menu in the server details?

Two actions for calling the often-used "details" seems to much. The "delete" action is called rarely, for me possibly never..

![screenshot-2018-02-02 1](https://user-images.githubusercontent.com/1172106/35741070-203955a0-0837-11e8-9f8a-a92cde96d523.jpg)

**Comment by LKDevelopment** [comment]
I've edit it, if you click on the item now you go to the Details Page and if you swipe to the right you could delete the Server or Project. Thank you for the Idea. I let the issue open, and try to submit a new build to apple today.

**Comment by janxb** [comment]
One additional remark on your change: the default swipe direction (at least on Apple devices) is right-to-left for delete. Maybe it would make sense to keep it the same in this app, for being consistent with the rest of the operating system.

**Comment by LKDevelopment** [comment]
Thanks fixed :)

**Comment by LKDevelopment** [comment]
With https://github.com/LKDevelopment/hetzner-cloud-mobile-app/commit/fbb5ca2b54019d443e3c8ed557b4295ddb7594dc all swipe actions are removed and replaced with Actions Cheets or direct clicks
