### ISSUE TITLE
Too much white space on screen borders

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#15]
Nearly every app screen has too much white space on the left and right borders of the screen. Maybe this is caused by a default resolution, or the used development framework default settings? Maybe the content can be made a little bit wider, so that the space is not wasted.

See the attached screenshots for examples. It is the most visible on the server list, where the search bar also has white space around it.

![screenshot-2018-02-02 2](https://user-images.githubusercontent.com/1172106/35741463-31f56b8e-0838-11e8-8679-752f0b6f2991.jpg)
![screenshot-2018-02-02 3](https://user-images.githubusercontent.com/1172106/35741483-3a9d39ce-0838-11e8-86b5-a587d7ccee72.jpg)

**Comment by LKDevelopment** [comment]
Fixed locally :) Thank you!
