### ISSUE TITLE
Inconsistent button sizes

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#16]
In app version 0.0.8 there are some buttons with smaller size than others. This is the most obvious in the backup config screen. See the attached screenshot for an example.

![2e22152b-f8f3-4172-9738-5f8e4c5e4d41](https://user-images.githubusercontent.com/1172106/35756001-d59144bc-0869-11e8-8103-db7bbe9fd3cc.png)

**Comment by LKDevelopment** [comment]
Fixed Thank you! Goes into the next Version (>0.0.9) because the builds for 0.0.9 are already submited.
