### ISSUE TITLE
No visual feedback on status notification settings save

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#19]
When pressing the "Save" button for the new Hetzner status notifications, there is no visual feedback confirming if the settings have been saved.

Maybe you could just close the configuration dialog if the settings have been saved? Or even better, just save them on-the-fly whenever a radio button is toggled.

**Comment by LKDevelopment** [comment]
Thanks, there should be a visual feedback. Will fix it asap.
