### ISSUE TITLE
No visual feedback on "create server" touch event

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#2]
When creating a new server, there is no visual feedback (like a loading indicator) after pressing the "Create Server" button. It just stays in the initial state for several seconds and then the server is created.

Maybe you could add a loading indicator or at least disable the button after the first press, so that it is clear that we are currently waiting for the API to respond.

Details: iOS 11.2.5 on iPhone 8

![screenshot-2018-02-01 1](https://user-images.githubusercontent.com/1172106/35673182-143f7280-0741-11e8-9a8a-c3f87098c0c0.jpg)

**Comment by LKDevelopment** [comment]
Done in the Master Branch, thank you! I will overhaul all forms, that there is a loading indicator.
