### ISSUE TITLE
Typo unwiederruflich / unwiderruflich

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#23]
Found a typo.. ;)
See here for more info: https://www.korrekturen.de/beliebte_fehler/unwiederruflich.shtml

https://github.com/LKDevelopment/hetzner-cloud-mobile-app/blob/8e704e7dcc18a2b43c71c8f497d85521e16e7c2b/src/pages/server/server.ts#L96

**Comment by LKDevelopment** [comment]
Thank you! i should refresh github more often :D just packaged & uploaded the 0.0.15 to the stores....
