### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by MaximilianSchieder** [LKDevelopment/hetzner-cloud-mobile-app#25]
Is there any plane to add an u2f (Yubikey etc.) RFID 2nd factor to the app?

//Maxi

**Comment by LKDevelopment** [comment]
Nice Idea! Will proof it.

**Comment by janxb** [comment]
If this is implemented, it should be not connected to the Hetzner 2FA, but be separately configurable within the app. I have 2FA enabled in the cloud web interface, but it would be inconvenient to also have the second factor in the app.

Maybe it would be easier to support TouchID / fingerprint authentication. This is an API which is supported directly by operating systems.

**Comment by LKDevelopment** [comment]
@janxb yeah i think this would be the better solution.

Implementation-Notice: https://ionicframework.com/docs/native/fingerprint-aio/

**Comment by LKDevelopment** [comment]
@MaximilianSchieder do you have a Android Phone or iOS?

**Comment by MaximilianSchieder** [comment]
I have an android phone. Yeah! Fingeprint should to work too!

**Comment by LKDevelopment** [comment]
![](https://i.imgur.com/fqWFCW8.png)

If you Update in Android it should Work now :)
