### ISSUE TITLE
Multi-Language Support

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#28]
Whats about multi language support for this app? Currently every message string is hard-coded into the source code, would it be possible to move this to separate files per language, so that we are able to maintain translations and messages independent from the main app?

I know, this may be a lot of work, but i'm asking anyways.. 😋

**Comment by LKDevelopment** [comment]
Yeah this is a nice Idea. I've asked the Hetzner GmbH if they wished this feature in the app. Actually i'm waiting on the answer.

**Comment by MaximilianSchieder** [comment]
Ohhh community driven translation would be very nice.

**Comment by janxb** [comment]
If the translations are moved to individual files here in this repository, changes could simply be made by creating pull requests :)

**Comment by LKDevelopment** [comment]
Yeah i will try to Implement this tomorrow as json key: values

**Comment by LKDevelopment** [comment]
So i made progress on this :) Actually ~40 % of the app is now in the language file. (/src/assets/i18n/de.json) I keep on working, so i think in ~1 or 2 hours it should be done

**Comment by LKDevelopment** [comment]
So it is done :) All Pages are now translateable!!  Under: https://github.com/LKDevelopment/hetzner-cloud-mobile-app/tree/master/src/assets/i18n are now all files. Actually only the German Translation is complete.

**Comment by LKDevelopment** [comment]
And Version 0.0.18 contains it! It should be released now :)
