### ISSUE TITLE
Server search only matches complete names

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#3]
The search field in the servers view only matches the complete server name. No partial input is matched. See the attached screenshots for an example.

Details: iOS 11.2.5 on iPhone 8

![screenshot-2018-02-01 2](https://user-images.githubusercontent.com/1172106/35673733-aca23ff2-0742-11e8-89c4-f86b44893eee.jpg)
![screenshot-2018-02-01 3](https://user-images.githubusercontent.com/1172106/35673732-ac87a444-0742-11e8-93b7-24fcdc0b7175.jpg)

**Comment by LKDevelopment** [comment]
That is actually a limitation from the Hetzner Cloud API. If you call the API directly it is the same output.

**Comment by janxb** [comment]
Hm, that's not nice. Maybe the app could initially fetch all servers and then filter locally using partial matching?

**Comment by LKDevelopment** [comment]
Yeah, i've implemented this in the master branch.
