### ISSUE TITLE
[Metrics] Datepicker buttons are white text on white background

### ISSUE THREAD

**Issue by janxb** [LKDevelopment/hetzner-cloud-mobile-app#38]
The cancel/apply buttons in the datepicker on the metrics page are white text on white background. So you can't see them, press randomly and hope for the best.. ;)

![screenshot-2018-02-28](https://user-images.githubusercontent.com/1172106/36817276-d53153d2-1ce0-11e8-9b92-82464647e049.jpg)

**Comment by LKDevelopment** [comment]
Fixed as b67126a thank you!

Can't actually say when the next version will be released, because actually i'm working on the end 2 end tests for the whole app.
