### ISSUE TITLE
Implement Server Metrics

### ISSUE THREAD

**Issue by LKDevelopment** [LKDevelopment/hetzner-cloud-mobile-app#9]
Implement the Server Metrics Page as FAB 
API: https://docs.hetzner.cloud/#resources-servers-get-2
Icon: fas fa-chart-area
In the Cloud Console Hetzner uses: https://gionkunz.github.io/chartist-js/ for the graphs. Check if it is possible to use the same library for the app.

**Comment by LKDevelopment** [comment]
Is this really needed? @janxb what do you think about it?

**Comment by janxb** [comment]
Metrics are always a nice thing.. ;) depends on implementation difficulty I think. The API endpoint seems like it‘s straightforward to use.

**Comment by LKDevelopment** [comment]
Done with 8e704e7
